[allowlist]
  description = "Global Allowlist"

  paths = [
    # Ignore htpasswd user files
    '''tenants\/openshift-day\/cluster-auth\/base\/users\.htpasswd$''',
    '''components\/cluster-configs\/htpasswd\/base\/users\.htpasswd$''',
  ]
